spring.application.name=msvc_auth-service
server.port=8085


spring.datasource.url=jdbc:h2:file:./data/auth-service
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
# Desactiva la UI local del microservicio, dejando activo solo el JSON de documentación
springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.path=/docs/swagger-ui.html

# Forzar el encendido del cliente Eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# URL exacta del servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Registro en Eureka. spring.application.name (arriba) es el nombre con que queda registrado.
eureka.instance.prefer-ip-address=true

# Excluir la configuración automática de Springdoc HATEOAS incompatible con Spring Boot 4.x
spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocHateoasConfiguration

# Desactivar por completo el cliente de descubrimiento y registro en Eureka
spring.cloud.discovery.enabled=false